version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile-build
    command: sh -c "npm install && npm test"
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    # volumes:
    #   - ./:/usr/src/app
    depends_on:
      - redis
  
  redis: 
    image: redis
    # ports: 
    #   - '6379:6379'