version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile.build
    command: sh -c "npm install"
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    links:
      - redis
  
  redis: 
    image: redis
    expose:
      - 6379