version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    working_dir: /usr/src/app
    links:
      - redis
  
  redis: 
    image: redis
    expose:
      - 6379
    command: ["redis-server", "--bind", "redis", "--port", "${REDIS_PORT}"]
