version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    links:
      - redis
  
  redis: 
    image: redis
    expose:
      - 6379